export default {
  YOUR_INFORMATIONS: 'YOUR_INFORMATIONS',
  SETTINGS: 'SETTINGS',
  MANAGE_USERS: 'MANAGE_USERS',
  HAVE_ACCOUNT: 'HAVE_ACCOUNT',
  PROFILE_INFORMATIONS: 'PROFILE_INFORMATIONS',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD'
};
