export default {
  HEIGHT_RANGE: 'HEIGHT_RANGE',
  WEIGHT_RANGE: 'WEIGHT_RANGE',
  MAN_SHOULDER_TYPE: 'MAN_SHOULDER_TYPE',
  MAN_STOMACH_TYPE: 'MAN_STOMACH_TYPE',
  MAN_HIP_TYPE: 'MAN_HIP_TYPE',
  WOMAN_CHEST_TYPE: 'WOMAN_CHEST_TYPE',
  WOMAN_STOMACH_TYPE: 'WOMAN_STOMACH_TYPE',
  WOMAN_HIP_TYPE: 'WOMAN_HIP_TYPE',
  AGE: 'AGE',
  FIT_CHOICE: 'FIT_CHOICE'
};
